language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - extra-android-support

jdk:
  - oraclejdk7
  - openjdk7

before_install:
   - chmod +x gradlew
